### ISSUE TITLE
Browser Extension builds Intervals Differently was: Poorly Written Intervals logs

### ISSUE THREAD

**Issue by poorejc** [apache/flagon-useralejs#13]
We are seeing multiple interval logs written with same start, but different end-times and counts. 

{
    "@timestamp": "2018-03-23T20:31:39.542Z",
    "count": 2,
    "duration": 3818557,
    "endTime": 1521837223993,
    "host": "172.18.0.1",
    "logType": "interval",
    "major_ver": "1",
    "minor_ver": "0",
    "pageUrl": "https://confluence.draper.com/display/TF/Jedi+Slide+Decks+and+Write+Ups",
    "patch_ver": "0",
    "path": [
        "div#main. aui-page-panel",
        "div.ia-splitter",
        "div#full-height-container",
        "div#page",
        "body#com-atlassian-confluence.theme-default aui-layout aui-theme-default synchrony-active",
        "shadow",
        "#document-fragment",
        "html",
        "#document",
        "Window"
    ],
    "sessionID": "session_1521544103912",
    "startTime": 1521833405436,
    "target": "div#main. aui-page-panel",
    "targetChange": true,
    "toolName": "test_app",
    "toolVersion": null,
    "type": "click",
    "typeChange": true,
    "userAction": false,
    "userId": "bqw0205",
    "useraleVersion": "1.0.0"
}

{
    "@timestamp": "2018-03-23T20:31:39.542Z",
    "count": 4,
    "duration": 3819958,
    "endTime": 1521837225394,
    "host": "172.18.0.1",
    "logType": "interval",
    "major_ver": "1",
    "minor_ver": "0",
    "pageUrl": "https://confluence.draper.com/display/TF/Jedi+Slide+Decks+and+Write+Ups",
    "patch_ver": "0",
    "path": [
        "div#main. aui-page-panel",
        "div.ia-splitter",
        "div#full-height-container",
        "div#page",
        "body#com-atlassian-confluence.theme-default aui-layout aui-theme-default synchrony-active",
        "shadow",
        "#document-fragment",
        "html",
        "#document",
        "Window"
    ],
    "sessionID": "session_1521544103912",
    "startTime": 1521833405436,
    "target": "div#main. aui-page-panel",
    "targetChange": true,
    "toolName": "test_app",
    "toolVersion": null,
    "type": "click",
    "typeChange": true,
    "userAction": false,
    "userId": "bqw0205",
    "useraleVersion": "1.0.0"
}

**Comment by Jyyjy** [comment]
Not seeing this bug today with mouse over events from the plugin. Maybe there are more specific conditions for this bug, or maybe this was inadvertently fixed in the last 4 years.

**Comment by EandrewJones** [comment]
Closing this as stale. If we encounter again, can be re-opened.

**Comment by EandrewJones** [comment]
Closing as stale. Can be re-opened if we see again.
