### ISSUE TITLE
Explore OpenTelemetry User-Interaction Libraries

### ISSUE THREAD

**Issue by poorejc** [apache/flagon-useralejs#19]
OpenTelemetry has a plugin that instruments the client for Click data, and attaches a traceID to logs. Should explore the project and see if we can't bring similar functionality into UserALE.js. OpenTelementry is ALv2.

**Comment by brucearctor** [comment]
@poorejc - is this still desired, is > 2 years old.  Also, "explore" invites a vague notion of completion, hence why I prod on this one :-)

**Comment by Jyyjy** [comment]
We did some exploration of open telemetry here:

https://github.com/UMD-ARLIS/incubator-flagon-useralejs/tree/OTintegration

Ultimately, the OT library required node features that are not pollyfilled in the rollup ecosystem. We were able to demonstrate an example with webpack that combined userale and OT. But integrating OT into userale would require migrating away from rollup.

Maybe by now there's a supporting rollup polyfill, or some other work around.

**Comment by EandrewJones** [comment]
@Jyyjy Flagging you as you've been getting involved in the OTEL Client instrumentation SIG.

At this point, I think this ticket is more of a confluence documentation ticket, at best. Share any ideas or insights about how Flagon more broadly (probably Distill, not UserALE) could play nice with OTel.

If you feel there's not much to share at this point, then let's just close the issue as stale.

**Comment by EandrewJones** [comment]
Closing this as it merits discussion on the dev email list or in a community meeting where it can get more exposure.
