### ISSUE TITLE
manifest v2 deprecates in 2023: modernize manifest for Browser Extension

### ISSUE THREAD

**Issue by poorejc** [apache/flagon-useralejs#237]
manifest v2 deprecates in 2023: modernize manifest for Browser Extension

**Comment by brucearctor** [comment]
@poorejc -- this is addressed and can be closed, is that correct ( per https://github.com/apache/incubator-flagon-useralejs/pull/286 )?

**Comment by EandrewJones** [comment]
Covered by #421 which is WIP
