### ISSUE TITLE
Update Rollup.js to v. 3

### ISSUE THREAD

**Issue by poorejc** [apache/flagon-useralejs#374]
In v.3 Rollup changed its methods for specifying different plugin specs, looks like this is breaking tests. should be an easy update but will require more integration testing. See #371 

[!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag. #

**Comment by Jyyjy** [comment]
The new Rollup version moves from CommonJS to an ES module format for the config. A quick fix is to add `--bundleConfigAsCjs`, which will treat the config as CommonJS. Alternatively, we could change `rollup.config.js` to ES module syntax.

https://rollupjs.org/migration/
