### ISSUE TITLE
CI(gh actions): Improve GH action suite

### ISSUE THREAD

**Issue by EandrewJones** [apache/flagon-useralejs#448]
## Problem
Our GH action suite is sparse and only automates testing. We are leaving a lot of the table. We could be enforcing far more checks to save ourselves headaches during releases.

## Solution
Add GH actions to enforce:
- [ ] linting
- [ ] type checking
- [ ] formatting
- [ ] [skywalking-eyes](https://github.com/apache/skywalking-eyes) for license compliance
- [ ] Automatic Release notes
- [ ] [Cronjobs](https://medium.com/nerd-for-tech/lets-run-cron-jobs-using-github-actions-df64496ffc4a) for automatically triggering new release candidates

> *_NOTE:_* These probably should be broken into separate tickets.

**Comment by Jyyjy** [comment]
If linting, type checking, and formatting are done as pre commit hooks, can we run precommit hooks in a GH action? Then there is a single place where these things are defined.

[Relevant GH action](https://github.com/pre-commit/action)

**Comment by EandrewJones** [comment]
Well the config files are the single source of truth for both in this case.
Husky is not like like python where it's referencing rules from external
places. It's just running npm commands.

Best

Evan Jones
Website: www.ea-jones.com

**Comment by rc10house** [comment]
Assigned to me

**Comment by rc10house** [comment]
Created PR rc10house:448-improve-GH-actions
