### ISSUE TITLE
Consider Cypress tests to flex wide range of .options API behavior

### ISSUE THREAD

**Issue by poorejc** [apache/flagon-useralejs#60]
Recent bug reports show, for example, behavior where reducing the latency between log shipments, and trimming the package size results in dropping logs that should be sent before a page unloads. Currently, unit tests and integration tests dont flex the range of options like this (string options are easier to test for --logging endpoint, userId, sessionID, etc.). Would be good test test for these edge-cases.

**Comment by brucearctor** [comment]
Ideally this can be scoped to specific tasks to know when complete?

**Comment by EandrewJones** [comment]
We expanded the e2e test suite and migrated to Playwright in #466. While it doesn't address all edge cases in the options API, it does provide expanded coverage of the package, especially the plugin and exposed numerous issues that we fixed.

Closing for now and recommend we scope future tickets to concrete test cases.
